default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  password: root
  database: ufacode_development

test:
  <<: *default
  password: root
  database: ufacode_test

production:
  <<: *default
  database: ufacode_production
  username: ufacode
  password: <%= ENV['UFACODE_DATABASE_PASSWORD'] %>
